# data voor odoosparcie met Postgres op Azure
version: '2'

services:
  odoo:
    tty: true
    stdin_open: true
    image: odoo
    ports:
      - 80:8069
    environment:
      - HOST=<host
      - USER=odoo
      - PASSWORD=<odoopass
      - DB_NAME=eteq
      - POSTGRES_DB=postgres
      - ADMIN_PASSWD="100%Koffie"
